@startgantt
@startgantt
projectscale weekly
Project starts the 16th of October 2023
' saturday are closed
' sunday are closed

-- Design --

[Use Case/Requirement Gathering] as [design-reqs] lasts 14 days
[Get Yaml Proposals] as [yaml-proposals] lasts 10 days and starts after [design-reqs]'s end
[NB API Yaml Design] as [api-design] lasts 20 days and starts after [design-reqs]'s end
[Design Complete] as [design-complete] happens at [api-design]'s end

-- Testing --

[Build Test Environment] as [test-build] lasts 14 days and starts after [design-complete]'s end
[Mock Up Server Generation] as [mock-server] lasts 7 days and starts after [test-build]'s end
[Test Cases] as [test-cases] lasts 14 days and starts after [test-build]'s end
[Testing Completed] happens at [test-cases]'s end

@endgantt