/*
 * LwM2M NB APIs
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package main

import (
	"log"
	"net/http"

	openapi "github.com/GIT_USER_ID/GIT_REPO_ID/go"
)

func main() {
	log.Printf("Server started")

	DeviceAPIService := openapi.NewDeviceAPIService()
	DeviceAPIController := openapi.NewDeviceAPIController(DeviceAPIService)

	router := openapi.NewRouter(DeviceAPIController)

	log.Fatal(http.ListenAndServe(":8080", router))
}
