/*
 * LwM2M NB APIs
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"context"
	"net/http"
)



// DeviceAPIRouter defines the required methods for binding the api requests to a responses for the DeviceAPI
// The DeviceAPIRouter implementation should parse necessary information from the http request,
// pass the data to a DeviceAPIServicer to perform the required actions, then write the service results to the http response.
type DeviceAPIRouter interface { 
	GetDevice(http.ResponseWriter, *http.Request)
}


// DeviceAPIServicer defines the api actions for the DeviceAPI service
// This interface intended to stay up to date with the openapi yaml used to generate it,
// while the service implementation can be ignored with the .openapi-generator-ignore file
// and updated with the logic required for the API.
type DeviceAPIServicer interface { 
	GetDevice(context.Context, string) (ImplResponse, error)
}
