openapi: "3.0.0"
info:
  title: LwM2M NB APIs
  version: 1.1.0

servers:
  - url: https://example.com

security:
  - ApiKeyAuth: []
  - OAuth2: []

tags:
  - name: Device

paths:
  /lwm2m/v1/devices/{deviceId}:
    get:
      summary: Get device information
      operationId: getDevice
      tags:
        - Device
      parameters:
        - name: deviceId
          in: path
          description: Identifier of the device
          required: true
          schema:
            type: string
      responses:
        200:
          description: Device information
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Device"
        401:
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GenericError"
        404:
          description: deviceId not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GenericError"

components:
  schemas:
    GenericError:
      type: object
      properties:
        code:
          type: string
          example:
            "error_0"
        message:
          type: string
          example:
            "An error occurred"
    Device:
      type: object
      properties:
        endpointName:
          type: string
          example: "example-client"
          readOnly: true
        binding:
          type: string
          example: "U"
        lwM2MVersion:
          type: string
          example: "1.0"
        registration:
          type: string
          format: date-time
          example: "2022-04-01T08:25:31.422+00:00"
        lifetime:
          type: number
          example: 300
        objects:
          type: array
          items:
            type: object
            properties:
              objectId:
                type: integer
                example: 1
              objectInstanceId:
                type: integer
                example: 0
              objectVersion:
                type: string
                example: "1.0"
