/*
 * LwM2M NB APIs
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"context"
	"net/http"
	"errors"
)

// DeviceOperationAPIService is a service that implements the logic for the DeviceOperationAPIServicer
// This service should implement the business logic for every endpoint for the DeviceOperationAPI API.
// Include any external packages or services that will be required by this service.
type DeviceOperationAPIService struct {
}

// NewDeviceOperationAPIService creates a default api service
func NewDeviceOperationAPIService() DeviceOperationAPIServicer {
	return &DeviceOperationAPIService{}
}

// CreateDeviceOperation - Create a new device operation
func (s *DeviceOperationAPIService) CreateDeviceOperation(ctx context.Context, deviceId string, createOperation CreateOperation) (ImplResponse, error) {
	// TODO - update CreateDeviceOperation with the required logic for this service method.
	// Add api_device_operation_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(202, CreatedOperationResult{}) or use other options such as http.Ok ...
	// return Response(202, CreatedOperationResult{}), nil

	// TODO: Uncomment the next line to return response Response(400, GenericError{}) or use other options such as http.Ok ...
	// return Response(400, GenericError{}), nil

	// TODO: Uncomment the next line to return response Response(401, GenericError{}) or use other options such as http.Ok ...
	// return Response(401, GenericError{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("CreateDeviceOperation method not implemented")
}

// DeleteDeviceOperation - Delete a completed device operation
func (s *DeviceOperationAPIService) DeleteDeviceOperation(ctx context.Context, deviceId string, operationId string) (ImplResponse, error) {
	// TODO - update DeleteDeviceOperation with the required logic for this service method.
	// Add api_device_operation_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(204, {}) or use other options such as http.Ok ...
	// return Response(204, nil),nil

	// TODO: Uncomment the next line to return response Response(401, GenericError{}) or use other options such as http.Ok ...
	// return Response(401, GenericError{}), nil

	// TODO: Uncomment the next line to return response Response(403, GenericError{}) or use other options such as http.Ok ...
	// return Response(403, GenericError{}), nil

	// TODO: Uncomment the next line to return response Response(404, GenericError{}) or use other options such as http.Ok ...
	// return Response(404, GenericError{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("DeleteDeviceOperation method not implemented")
}

// GetDeviceOperation - Get the state of a device operation
func (s *DeviceOperationAPIService) GetDeviceOperation(ctx context.Context, deviceId string, operationId string) (ImplResponse, error) {
	// TODO - update GetDeviceOperation with the required logic for this service method.
	// Add api_device_operation_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, DeviceOperation{}) or use other options such as http.Ok ...
	// return Response(200, DeviceOperation{}), nil

	// TODO: Uncomment the next line to return response Response(401, GenericError{}) or use other options such as http.Ok ...
	// return Response(401, GenericError{}), nil

	// TODO: Uncomment the next line to return response Response(404, GenericError{}) or use other options such as http.Ok ...
	// return Response(404, GenericError{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("GetDeviceOperation method not implemented")
}

// GetDeviceOperationErrorTargets - Get device operation error targets
func (s *DeviceOperationAPIService) GetDeviceOperationErrorTargets(ctx context.Context, deviceId string, operationId string, page int32, size int32) (ImplResponse, error) {
	// TODO - update GetDeviceOperationErrorTargets with the required logic for this service method.
	// Add api_device_operation_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, GetDeviceOperationErrorTargets200Response{}) or use other options such as http.Ok ...
	// return Response(200, GetDeviceOperationErrorTargets200Response{}), nil

	// TODO: Uncomment the next line to return response Response(401, GenericError{}) or use other options such as http.Ok ...
	// return Response(401, GenericError{}), nil

	// TODO: Uncomment the next line to return response Response(404, GenericError{}) or use other options such as http.Ok ...
	// return Response(404, GenericError{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("GetDeviceOperationErrorTargets method not implemented")
}

// GetDeviceOperationSuccessTargets - Get device operation success targets
func (s *DeviceOperationAPIService) GetDeviceOperationSuccessTargets(ctx context.Context, deviceId string, operationId string, page int32, size int32) (ImplResponse, error) {
	// TODO - update GetDeviceOperationSuccessTargets with the required logic for this service method.
	// Add api_device_operation_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, GetDeviceOperationSuccessTargets200Response{}) or use other options such as http.Ok ...
	// return Response(200, GetDeviceOperationSuccessTargets200Response{}), nil

	// TODO: Uncomment the next line to return response Response(401, GenericError{}) or use other options such as http.Ok ...
	// return Response(401, GenericError{}), nil

	// TODO: Uncomment the next line to return response Response(404, GenericError{}) or use other options such as http.Ok ...
	// return Response(404, GenericError{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("GetDeviceOperationSuccessTargets method not implemented")
}

// GetDeviceOperations - Get all the device operations
func (s *DeviceOperationAPIService) GetDeviceOperations(ctx context.Context, deviceId string, page int32, size int32) (ImplResponse, error) {
	// TODO - update GetDeviceOperations with the required logic for this service method.
	// Add api_device_operation_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, GetDeviceOperations200Response{}) or use other options such as http.Ok ...
	// return Response(200, GetDeviceOperations200Response{}), nil

	// TODO: Uncomment the next line to return response Response(401, GenericError{}) or use other options such as http.Ok ...
	// return Response(401, GenericError{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("GetDeviceOperations method not implemented")
}
