/*
 * LwM2M NB APIs
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"context"
	"net/http"
	"errors"
)

// DeviceObservationAPIService is a service that implements the logic for the DeviceObservationAPIServicer
// This service should implement the business logic for every endpoint for the DeviceObservationAPI API.
// Include any external packages or services that will be required by this service.
type DeviceObservationAPIService struct {
}

// NewDeviceObservationAPIService creates a default api service
func NewDeviceObservationAPIService() DeviceObservationAPIServicer {
	return &DeviceObservationAPIService{}
}

// CreateDeviceObservation - Create a new device observation
func (s *DeviceObservationAPIService) CreateDeviceObservation(ctx context.Context, deviceId string, createObservation CreateObservation) (ImplResponse, error) {
	// TODO - update CreateDeviceObservation with the required logic for this service method.
	// Add api_device_observation_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, CreatedObservationResult{}) or use other options such as http.Ok ...
	// return Response(200, CreatedObservationResult{}), nil

	// TODO: Uncomment the next line to return response Response(400, GenericError{}) or use other options such as http.Ok ...
	// return Response(400, GenericError{}), nil

	// TODO: Uncomment the next line to return response Response(401, GenericError{}) or use other options such as http.Ok ...
	// return Response(401, GenericError{}), nil

	// TODO: Uncomment the next line to return response Response(404, GenericError{}) or use other options such as http.Ok ...
	// return Response(404, GenericError{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("CreateDeviceObservation method not implemented")
}

// DeleteDeviceObservation - Delete a device observation
func (s *DeviceObservationAPIService) DeleteDeviceObservation(ctx context.Context, deviceId string, observationId string) (ImplResponse, error) {
	// TODO - update DeleteDeviceObservation with the required logic for this service method.
	// Add api_device_observation_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(204, {}) or use other options such as http.Ok ...
	// return Response(204, nil),nil

	// TODO: Uncomment the next line to return response Response(401, GenericError{}) or use other options such as http.Ok ...
	// return Response(401, GenericError{}), nil

	// TODO: Uncomment the next line to return response Response(404, GenericError{}) or use other options such as http.Ok ...
	// return Response(404, GenericError{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("DeleteDeviceObservation method not implemented")
}

// GetDeviceObservation - Get the state of a device observation
func (s *DeviceObservationAPIService) GetDeviceObservation(ctx context.Context, deviceId string, observationId string) (ImplResponse, error) {
	// TODO - update GetDeviceObservation with the required logic for this service method.
	// Add api_device_observation_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, Observation{}) or use other options such as http.Ok ...
	// return Response(200, Observation{}), nil

	// TODO: Uncomment the next line to return response Response(401, GenericError{}) or use other options such as http.Ok ...
	// return Response(401, GenericError{}), nil

	// TODO: Uncomment the next line to return response Response(404, GenericError{}) or use other options such as http.Ok ...
	// return Response(404, GenericError{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("GetDeviceObservation method not implemented")
}

// GetDeviceObservationNotification - Get the notification of a device observation
func (s *DeviceObservationAPIService) GetDeviceObservationNotification(ctx context.Context, deviceId string, observationId string, notificationId string) (ImplResponse, error) {
	// TODO - update GetDeviceObservationNotification with the required logic for this service method.
	// Add api_device_observation_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, ObservationDataNotification{}) or use other options such as http.Ok ...
	// return Response(200, ObservationDataNotification{}), nil

	// TODO: Uncomment the next line to return response Response(401, GenericError{}) or use other options such as http.Ok ...
	// return Response(401, GenericError{}), nil

	// TODO: Uncomment the next line to return response Response(404, GenericError{}) or use other options such as http.Ok ...
	// return Response(404, GenericError{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("GetDeviceObservationNotification method not implemented")
}

// GetDeviceObservationNotifications - Get the device observation&#39;s notifications
func (s *DeviceObservationAPIService) GetDeviceObservationNotifications(ctx context.Context, deviceId string, observationId string, page int32, size int32) (ImplResponse, error) {
	// TODO - update GetDeviceObservationNotifications with the required logic for this service method.
	// Add api_device_observation_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, GetDeviceObservationNotifications200Response{}) or use other options such as http.Ok ...
	// return Response(200, GetDeviceObservationNotifications200Response{}), nil

	// TODO: Uncomment the next line to return response Response(400, GenericError{}) or use other options such as http.Ok ...
	// return Response(400, GenericError{}), nil

	// TODO: Uncomment the next line to return response Response(401, GenericError{}) or use other options such as http.Ok ...
	// return Response(401, GenericError{}), nil

	// TODO: Uncomment the next line to return response Response(404, GenericError{}) or use other options such as http.Ok ...
	// return Response(404, GenericError{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("GetDeviceObservationNotifications method not implemented")
}

// GetDeviceObservations - Get all the device observations
func (s *DeviceObservationAPIService) GetDeviceObservations(ctx context.Context, deviceId string, page int32, size int32) (ImplResponse, error) {
	// TODO - update GetDeviceObservations with the required logic for this service method.
	// Add api_device_observation_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, GetDeviceObservations200Response{}) or use other options such as http.Ok ...
	// return Response(200, GetDeviceObservations200Response{}), nil

	// TODO: Uncomment the next line to return response Response(401, GenericError{}) or use other options such as http.Ok ...
	// return Response(401, GenericError{}), nil

	// TODO: Uncomment the next line to return response Response(404, GenericError{}) or use other options such as http.Ok ...
	// return Response(404, GenericError{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("GetDeviceObservations method not implemented")
}
