/*
 * LwM2M NB APIs
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"context"
	"net/http"
	"errors"
)

// DeviceAPIService is a service that implements the logic for the DeviceAPIServicer
// This service should implement the business logic for every endpoint for the DeviceAPI API.
// Include any external packages or services that will be required by this service.
type DeviceAPIService struct {
}

// NewDeviceAPIService creates a default api service
func NewDeviceAPIService() DeviceAPIServicer {
	return &DeviceAPIService{}
}

// GetDevice - Get device information
func (s *DeviceAPIService) GetDevice(ctx context.Context, deviceId string) (ImplResponse, error) {
	// TODO - update GetDevice with the required logic for this service method.
	// Add api_device_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, Device{}) or use other options such as http.Ok ...
	// return Response(200, Device{}), nil

	// TODO: Uncomment the next line to return response Response(401, GenericError{}) or use other options such as http.Ok ...
	// return Response(401, GenericError{}), nil

	// TODO: Uncomment the next line to return response Response(404, GenericError{}) or use other options such as http.Ok ...
	// return Response(404, GenericError{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("GetDevice method not implemented")
}
