/*
 * LwM2M NB APIs
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi


import (
	"time"
)



type SingleOperationDataReport struct {

	Path string `json:"path"`

	Value map[string]interface{} `json:"value"`

	ValueType string `json:"valueType,omitempty"`

	DeviceTimestamp time.Time `json:"deviceTimestamp,omitempty"`

	ServerTimestamp time.Time `json:"serverTimestamp"`
}

// AssertSingleOperationDataReportRequired checks if the required fields are not zero-ed
func AssertSingleOperationDataReportRequired(obj SingleOperationDataReport) error {
	elements := map[string]interface{}{
		"path": obj.Path,
		"value": obj.Value,
		"serverTimestamp": obj.ServerTimestamp,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertSingleOperationDataReportConstraints checks if the values respects the defined constraints
func AssertSingleOperationDataReportConstraints(obj SingleOperationDataReport) error {
	return nil
}
