/*
 * LwM2M NB APIs
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi




type GenericError struct {

	Code string `json:"code,omitempty"`

	Message string `json:"message,omitempty"`
}

// AssertGenericErrorRequired checks if the required fields are not zero-ed
func AssertGenericErrorRequired(obj GenericError) error {
	return nil
}

// AssertGenericErrorConstraints checks if the values respects the defined constraints
func AssertGenericErrorConstraints(obj GenericError) error {
	return nil
}
