/*
 * LwM2M NB APIs
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi


import (
	"time"
)



type Observation struct {

	CreationDate time.Time `json:"creationDate,omitempty"`

	Targets []ObservationAllOfTargets `json:"targets,omitempty"`
}

// AssertObservationRequired checks if the required fields are not zero-ed
func AssertObservationRequired(obj Observation) error {
	for _, el := range obj.Targets {
		if err := AssertObservationAllOfTargetsRequired(el); err != nil {
			return err
		}
	}
	return nil
}

// AssertObservationConstraints checks if the values respects the defined constraints
func AssertObservationConstraints(obj Observation) error {
	return nil
}
