/*
 * LwM2M NB APIs
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi


import (
	"time"
)



type Device struct {

	EndpointName string `json:"endpointName,omitempty"`

	Binding string `json:"binding,omitempty"`

	LwM2MVersion string `json:"lwM2MVersion,omitempty"`

	Registration time.Time `json:"registration,omitempty"`

	Lifetime float32 `json:"lifetime,omitempty"`

	Objects []DeviceObjectsInner `json:"objects,omitempty"`

	Observations []Observation `json:"observations,omitempty"`

	Operations []DeviceOperation `json:"operations,omitempty"`
}

// AssertDeviceRequired checks if the required fields are not zero-ed
func AssertDeviceRequired(obj Device) error {
	for _, el := range obj.Objects {
		if err := AssertDeviceObjectsInnerRequired(el); err != nil {
			return err
		}
	}
	for _, el := range obj.Observations {
		if err := AssertObservationRequired(el); err != nil {
			return err
		}
	}
	for _, el := range obj.Operations {
		if err := AssertDeviceOperationRequired(el); err != nil {
			return err
		}
	}
	return nil
}

// AssertDeviceConstraints checks if the values respects the defined constraints
func AssertDeviceConstraints(obj Device) error {
	return nil
}
