/*
 * LwM2M NB APIs
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi




type ObservationDataNotification struct {

	DeviceId string `json:"deviceId,omitempty"`

	ObservationId string `json:"observationId,omitempty"`

	NotificationId string `json:"notificationId,omitempty"`

	Results []ResultDataNotification `json:"results,omitempty"`
}

// AssertObservationDataNotificationRequired checks if the required fields are not zero-ed
func AssertObservationDataNotificationRequired(obj ObservationDataNotification) error {
	for _, el := range obj.Results {
		if err := AssertResultDataNotificationRequired(el); err != nil {
			return err
		}
	}
	return nil
}

// AssertObservationDataNotificationConstraints checks if the values respects the defined constraints
func AssertObservationDataNotificationConstraints(obj ObservationDataNotification) error {
	return nil
}
