/*
 * LwM2M NB APIs
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi




type DeviceObjectsInner struct {

	ObjectId int32 `json:"objectId,omitempty"`

	ObjectInstanceId int32 `json:"objectInstanceId,omitempty"`

	ObjectVersion string `json:"objectVersion,omitempty"`
}

// AssertDeviceObjectsInnerRequired checks if the required fields are not zero-ed
func AssertDeviceObjectsInnerRequired(obj DeviceObjectsInner) error {
	return nil
}

// AssertDeviceObjectsInnerConstraints checks if the values respects the defined constraints
func AssertDeviceObjectsInnerConstraints(obj DeviceObjectsInner) error {
	return nil
}
