/*
 * LwM2M NB APIs
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi




type DeviceOperationAllOfTargets struct {

	Path string `json:"path,omitempty"`

	Value map[string]interface{} `json:"value,omitempty"`
}

// AssertDeviceOperationAllOfTargetsRequired checks if the required fields are not zero-ed
func AssertDeviceOperationAllOfTargetsRequired(obj DeviceOperationAllOfTargets) error {
	return nil
}

// AssertDeviceOperationAllOfTargetsConstraints checks if the values respects the defined constraints
func AssertDeviceOperationAllOfTargetsConstraints(obj DeviceOperationAllOfTargets) error {
	return nil
}
