openapi: 3.0.0
info:
  title: LwM2M NB APIs
  version: 1.1.0
servers:
- url: https://example.com
security:
- ApiKeyAuth: []
- OAuth2: []
tags:
- name: Device
paths:
  /lwm2m/v1/devices/{deviceId}:
    get:
      operationId: getDevice
      parameters:
      - description: Identifier of the device
        explode: false
        in: path
        name: deviceId
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Device'
          description: Device information
        "401":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GenericError'
          description: Unauthorized
        "404":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GenericError'
          description: deviceId not found
      summary: Get device information
      tags:
      - Device
components:
  schemas:
    GenericError:
      properties:
        code:
          example: error_0
          type: string
        message:
          example: An error occurred
          type: string
      type: object
    Device:
      example:
        lwM2MVersion: "1.0"
        objects:
        - objectVersion: "1.0"
          objectInstanceId: 0
          objectId: 1
        - objectVersion: "1.0"
          objectInstanceId: 0
          objectId: 1
        lifetime: 300
        endpointName: example-client
        binding: U
        registration: 2022-04-01T08:25:31.422Z
      properties:
        endpointName:
          example: example-client
          readOnly: true
          type: string
        binding:
          example: U
          type: string
        lwM2MVersion:
          example: "1.0"
          type: string
        registration:
          example: 2022-04-01T08:25:31.422Z
          format: date-time
          type: string
        lifetime:
          example: 300
          type: number
        objects:
          items:
            $ref: '#/components/schemas/Device_objects_inner'
          type: array
      type: object
    Device_objects_inner:
      example:
        objectVersion: "1.0"
        objectInstanceId: 0
        objectId: 1
      properties:
        objectId:
          example: 1
          type: integer
        objectInstanceId:
          example: 0
          type: integer
        objectVersion:
          example: "1.0"
          type: string
      type: object
