/*
 * LwM2M NB APIs
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"context"
	"net/http"
)



// DeviceAPIRouter defines the required methods for binding the api requests to a responses for the DeviceAPI
// The DeviceAPIRouter implementation should parse necessary information from the http request,
// pass the data to a DeviceAPIServicer to perform the required actions, then write the service results to the http response.
type DeviceAPIRouter interface { 
	GetDevice(http.ResponseWriter, *http.Request)
}
// DeviceObservationAPIRouter defines the required methods for binding the api requests to a responses for the DeviceObservationAPI
// The DeviceObservationAPIRouter implementation should parse necessary information from the http request,
// pass the data to a DeviceObservationAPIServicer to perform the required actions, then write the service results to the http response.
type DeviceObservationAPIRouter interface { 
	CreateDeviceObservation(http.ResponseWriter, *http.Request)
	DeleteDeviceObservation(http.ResponseWriter, *http.Request)
	GetDeviceObservation(http.ResponseWriter, *http.Request)
	GetDeviceObservationNotification(http.ResponseWriter, *http.Request)
	GetDeviceObservationNotifications(http.ResponseWriter, *http.Request)
	GetDeviceObservations(http.ResponseWriter, *http.Request)
}
// DeviceOperationAPIRouter defines the required methods for binding the api requests to a responses for the DeviceOperationAPI
// The DeviceOperationAPIRouter implementation should parse necessary information from the http request,
// pass the data to a DeviceOperationAPIServicer to perform the required actions, then write the service results to the http response.
type DeviceOperationAPIRouter interface { 
	CreateDeviceOperation(http.ResponseWriter, *http.Request)
	DeleteDeviceOperation(http.ResponseWriter, *http.Request)
	GetDeviceOperation(http.ResponseWriter, *http.Request)
	GetDeviceOperationErrorTargets(http.ResponseWriter, *http.Request)
	GetDeviceOperationSuccessTargets(http.ResponseWriter, *http.Request)
	GetDeviceOperations(http.ResponseWriter, *http.Request)
}


// DeviceAPIServicer defines the api actions for the DeviceAPI service
// This interface intended to stay up to date with the openapi yaml used to generate it,
// while the service implementation can be ignored with the .openapi-generator-ignore file
// and updated with the logic required for the API.
type DeviceAPIServicer interface { 
	GetDevice(context.Context, string) (ImplResponse, error)
}


// DeviceObservationAPIServicer defines the api actions for the DeviceObservationAPI service
// This interface intended to stay up to date with the openapi yaml used to generate it,
// while the service implementation can be ignored with the .openapi-generator-ignore file
// and updated with the logic required for the API.
type DeviceObservationAPIServicer interface { 
	CreateDeviceObservation(context.Context, string, CreateObservation) (ImplResponse, error)
	DeleteDeviceObservation(context.Context, string, string) (ImplResponse, error)
	GetDeviceObservation(context.Context, string, string) (ImplResponse, error)
	GetDeviceObservationNotification(context.Context, string, string, string) (ImplResponse, error)
	GetDeviceObservationNotifications(context.Context, string, string, int32, int32) (ImplResponse, error)
	GetDeviceObservations(context.Context, string, int32, int32) (ImplResponse, error)
}


// DeviceOperationAPIServicer defines the api actions for the DeviceOperationAPI service
// This interface intended to stay up to date with the openapi yaml used to generate it,
// while the service implementation can be ignored with the .openapi-generator-ignore file
// and updated with the logic required for the API.
type DeviceOperationAPIServicer interface { 
	CreateDeviceOperation(context.Context, string, CreateOperation) (ImplResponse, error)
	DeleteDeviceOperation(context.Context, string, string) (ImplResponse, error)
	GetDeviceOperation(context.Context, string, string) (ImplResponse, error)
	GetDeviceOperationErrorTargets(context.Context, string, string, int32, int32) (ImplResponse, error)
	GetDeviceOperationSuccessTargets(context.Context, string, string, int32, int32) (ImplResponse, error)
	GetDeviceOperations(context.Context, string, int32, int32) (ImplResponse, error)
}
