/*
 * LwM2M NB APIs
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"encoding/json"
	"net/http"
	"strings"

	"github.com/gorilla/mux"
)

// DeviceOperationAPIController binds http requests to an api service and writes the service results to the http response
type DeviceOperationAPIController struct {
	service DeviceOperationAPIServicer
	errorHandler ErrorHandler
}

// DeviceOperationAPIOption for how the controller is set up.
type DeviceOperationAPIOption func(*DeviceOperationAPIController)

// WithDeviceOperationAPIErrorHandler inject ErrorHandler into controller
func WithDeviceOperationAPIErrorHandler(h ErrorHandler) DeviceOperationAPIOption {
	return func(c *DeviceOperationAPIController) {
		c.errorHandler = h
	}
}

// NewDeviceOperationAPIController creates a default api controller
func NewDeviceOperationAPIController(s DeviceOperationAPIServicer, opts ...DeviceOperationAPIOption) Router {
	controller := &DeviceOperationAPIController{
		service:      s,
		errorHandler: DefaultErrorHandler,
	}

	for _, opt := range opts {
		opt(controller)
	}

	return controller
}

// Routes returns all the api routes for the DeviceOperationAPIController
func (c *DeviceOperationAPIController) Routes() Routes {
	return Routes{
		"CreateDeviceOperation": Route{
			strings.ToUpper("Post"),
			"/lwm2m/v1/devices/{deviceId}/operations",
			c.CreateDeviceOperation,
		},
		"DeleteDeviceOperation": Route{
			strings.ToUpper("Delete"),
			"/lwm2m/v1/devices/{deviceId}/operations/{operationId}",
			c.DeleteDeviceOperation,
		},
		"GetDeviceOperation": Route{
			strings.ToUpper("Get"),
			"/lwm2m/v1/devices/{deviceId}/operations/{operationId}",
			c.GetDeviceOperation,
		},
		"GetDeviceOperationErrorTargets": Route{
			strings.ToUpper("Get"),
			"/lwm2m/v1/devices/{deviceId}/operations/{operationId}/errorTargets",
			c.GetDeviceOperationErrorTargets,
		},
		"GetDeviceOperationSuccessTargets": Route{
			strings.ToUpper("Get"),
			"/lwm2m/v1/devices/{deviceId}/operations/{operationId}/successTargets",
			c.GetDeviceOperationSuccessTargets,
		},
		"GetDeviceOperations": Route{
			strings.ToUpper("Get"),
			"/lwm2m/v1/devices/{deviceId}/operations",
			c.GetDeviceOperations,
		},
	}
}

// CreateDeviceOperation - Create a new device operation
func (c *DeviceOperationAPIController) CreateDeviceOperation(w http.ResponseWriter, r *http.Request) {
	params := mux.Vars(r)
	deviceIdParam := params["deviceId"]
	if deviceIdParam == "" {
		c.errorHandler(w, r, &RequiredError{"deviceId"}, nil)
		return
	}
	createOperationParam := CreateOperation{}
	d := json.NewDecoder(r.Body)
	d.DisallowUnknownFields()
	if err := d.Decode(&createOperationParam); err != nil {
		c.errorHandler(w, r, &ParsingError{Err: err}, nil)
		return
	}
	if err := AssertCreateOperationRequired(createOperationParam); err != nil {
		c.errorHandler(w, r, err, nil)
		return
	}
	if err := AssertCreateOperationConstraints(createOperationParam); err != nil {
		c.errorHandler(w, r, err, nil)
		return
	}
	result, err := c.service.CreateDeviceOperation(r.Context(), deviceIdParam, createOperationParam)
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	EncodeJSONResponse(result.Body, &result.Code, w)
}

// DeleteDeviceOperation - Delete a completed device operation
func (c *DeviceOperationAPIController) DeleteDeviceOperation(w http.ResponseWriter, r *http.Request) {
	params := mux.Vars(r)
	deviceIdParam := params["deviceId"]
	if deviceIdParam == "" {
		c.errorHandler(w, r, &RequiredError{"deviceId"}, nil)
		return
	}
	operationIdParam := params["operationId"]
	if operationIdParam == "" {
		c.errorHandler(w, r, &RequiredError{"operationId"}, nil)
		return
	}
	result, err := c.service.DeleteDeviceOperation(r.Context(), deviceIdParam, operationIdParam)
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	EncodeJSONResponse(result.Body, &result.Code, w)
}

// GetDeviceOperation - Get the state of a device operation
func (c *DeviceOperationAPIController) GetDeviceOperation(w http.ResponseWriter, r *http.Request) {
	params := mux.Vars(r)
	deviceIdParam := params["deviceId"]
	if deviceIdParam == "" {
		c.errorHandler(w, r, &RequiredError{"deviceId"}, nil)
		return
	}
	operationIdParam := params["operationId"]
	if operationIdParam == "" {
		c.errorHandler(w, r, &RequiredError{"operationId"}, nil)
		return
	}
	result, err := c.service.GetDeviceOperation(r.Context(), deviceIdParam, operationIdParam)
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	EncodeJSONResponse(result.Body, &result.Code, w)
}

// GetDeviceOperationErrorTargets - Get device operation error targets
func (c *DeviceOperationAPIController) GetDeviceOperationErrorTargets(w http.ResponseWriter, r *http.Request) {
	params := mux.Vars(r)
	query := r.URL.Query()
	deviceIdParam := params["deviceId"]
	if deviceIdParam == "" {
		c.errorHandler(w, r, &RequiredError{"deviceId"}, nil)
		return
	}
	operationIdParam := params["operationId"]
	if operationIdParam == "" {
		c.errorHandler(w, r, &RequiredError{"operationId"}, nil)
		return
	}
	pageParam, err := parseNumericParameter[int32](
		query.Get("page"),
		WithParse[int32](parseInt32),
	)
	if err != nil {
		c.errorHandler(w, r, &ParsingError{Err: err}, nil)
		return
	}
	sizeParam, err := parseNumericParameter[int32](
		query.Get("size"),
		WithParse[int32](parseInt32),
	)
	if err != nil {
		c.errorHandler(w, r, &ParsingError{Err: err}, nil)
		return
	}
	result, err := c.service.GetDeviceOperationErrorTargets(r.Context(), deviceIdParam, operationIdParam, pageParam, sizeParam)
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	EncodeJSONResponse(result.Body, &result.Code, w)
}

// GetDeviceOperationSuccessTargets - Get device operation success targets
func (c *DeviceOperationAPIController) GetDeviceOperationSuccessTargets(w http.ResponseWriter, r *http.Request) {
	params := mux.Vars(r)
	query := r.URL.Query()
	deviceIdParam := params["deviceId"]
	if deviceIdParam == "" {
		c.errorHandler(w, r, &RequiredError{"deviceId"}, nil)
		return
	}
	operationIdParam := params["operationId"]
	if operationIdParam == "" {
		c.errorHandler(w, r, &RequiredError{"operationId"}, nil)
		return
	}
	pageParam, err := parseNumericParameter[int32](
		query.Get("page"),
		WithParse[int32](parseInt32),
	)
	if err != nil {
		c.errorHandler(w, r, &ParsingError{Err: err}, nil)
		return
	}
	sizeParam, err := parseNumericParameter[int32](
		query.Get("size"),
		WithParse[int32](parseInt32),
	)
	if err != nil {
		c.errorHandler(w, r, &ParsingError{Err: err}, nil)
		return
	}
	result, err := c.service.GetDeviceOperationSuccessTargets(r.Context(), deviceIdParam, operationIdParam, pageParam, sizeParam)
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	EncodeJSONResponse(result.Body, &result.Code, w)
}

// GetDeviceOperations - Get all the device operations
func (c *DeviceOperationAPIController) GetDeviceOperations(w http.ResponseWriter, r *http.Request) {
	params := mux.Vars(r)
	query := r.URL.Query()
	deviceIdParam := params["deviceId"]
	if deviceIdParam == "" {
		c.errorHandler(w, r, &RequiredError{"deviceId"}, nil)
		return
	}
	pageParam, err := parseNumericParameter[int32](
		query.Get("page"),
		WithParse[int32](parseInt32),
	)
	if err != nil {
		c.errorHandler(w, r, &ParsingError{Err: err}, nil)
		return
	}
	sizeParam, err := parseNumericParameter[int32](
		query.Get("size"),
		WithParse[int32](parseInt32),
	)
	if err != nil {
		c.errorHandler(w, r, &ParsingError{Err: err}, nil)
		return
	}
	result, err := c.service.GetDeviceOperations(r.Context(), deviceIdParam, pageParam, sizeParam)
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	EncodeJSONResponse(result.Body, &result.Code, w)
}
