/*
 * LwM2M NB APIs
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi




type GetDeviceOperationSuccessTargets200Response struct {

	TotalElements int32 `json:"totalElements,omitempty"`

	TotalPages int32 `json:"totalPages,omitempty"`

	PageSize int32 `json:"pageSize,omitempty"`

	Count int32 `json:"count,omitempty"`

	Page int32 `json:"page,omitempty"`

	NextPage string `json:"nextPage,omitempty"`

	Data []SingleOperationDataReport `json:"data,omitempty"`
}

// AssertGetDeviceOperationSuccessTargets200ResponseRequired checks if the required fields are not zero-ed
func AssertGetDeviceOperationSuccessTargets200ResponseRequired(obj GetDeviceOperationSuccessTargets200Response) error {
	for _, el := range obj.Data {
		if err := AssertSingleOperationDataReportRequired(el); err != nil {
			return err
		}
	}
	return nil
}

// AssertGetDeviceOperationSuccessTargets200ResponseConstraints checks if the values respects the defined constraints
func AssertGetDeviceOperationSuccessTargets200ResponseConstraints(obj GetDeviceOperationSuccessTargets200Response) error {
	return nil
}
