/*
 * LwM2M NB APIs
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi




type CreateOperationWithoutValueTargetsInner struct {

	Path string `json:"path"`
}

// AssertCreateOperationWithoutValueTargetsInnerRequired checks if the required fields are not zero-ed
func AssertCreateOperationWithoutValueTargetsInnerRequired(obj CreateOperationWithoutValueTargetsInner) error {
	elements := map[string]interface{}{
		"path": obj.Path,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertCreateOperationWithoutValueTargetsInnerConstraints checks if the values respects the defined constraints
func AssertCreateOperationWithoutValueTargetsInnerConstraints(obj CreateOperationWithoutValueTargetsInner) error {
	return nil
}
