/*
 * LwM2M NB APIs
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi




type CreateOperationWithValueTargetsInner struct {

	Path string `json:"path"`

	Value map[string]interface{} `json:"value"`
}

// AssertCreateOperationWithValueTargetsInnerRequired checks if the required fields are not zero-ed
func AssertCreateOperationWithValueTargetsInnerRequired(obj CreateOperationWithValueTargetsInner) error {
	elements := map[string]interface{}{
		"path": obj.Path,
		"value": obj.Value,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertCreateOperationWithValueTargetsInnerConstraints checks if the values respects the defined constraints
func AssertCreateOperationWithValueTargetsInnerConstraints(obj CreateOperationWithValueTargetsInner) error {
	return nil
}
