/*
 * LwM2M NB APIs
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi


import (
	"time"
)



type DeviceOperation struct {

	// The type of the operation
	Operation string `json:"operation,omitempty"`

	// The status of the operation
	Status string `json:"status,omitempty"`

	CompletenessDate time.Time `json:"completenessDate,omitempty"`

	Targets []DeviceOperationAllOfTargets `json:"targets,omitempty"`

	SuccessTargets int32 `json:"successTargets,omitempty"`

	ErrorTargets int32 `json:"errorTargets,omitempty"`

	CreationDate time.Time `json:"creationDate,omitempty"`
}

// AssertDeviceOperationRequired checks if the required fields are not zero-ed
func AssertDeviceOperationRequired(obj DeviceOperation) error {
	for _, el := range obj.Targets {
		if err := AssertDeviceOperationAllOfTargetsRequired(el); err != nil {
			return err
		}
	}
	return nil
}

// AssertDeviceOperationConstraints checks if the values respects the defined constraints
func AssertDeviceOperationConstraints(obj DeviceOperation) error {
	return nil
}
