/*
 * LwM2M NB APIs
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi




type CreateObservationTargetsInner struct {

	Path string `json:"path,omitempty"`
}

// AssertCreateObservationTargetsInnerRequired checks if the required fields are not zero-ed
func AssertCreateObservationTargetsInnerRequired(obj CreateObservationTargetsInner) error {
	return nil
}

// AssertCreateObservationTargetsInnerConstraints checks if the values respects the defined constraints
func AssertCreateObservationTargetsInnerConstraints(obj CreateObservationTargetsInner) error {
	return nil
}
