/*
 * LwM2M NB APIs
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi




type GetDeviceOperations200Response struct {

	TotalElements int32 `json:"totalElements,omitempty"`

	TotalPages int32 `json:"totalPages,omitempty"`

	PageSize int32 `json:"pageSize,omitempty"`

	Count int32 `json:"count,omitempty"`

	Page int32 `json:"page,omitempty"`

	NextPage string `json:"nextPage,omitempty"`

	Data []PaginatedDeviceOperation `json:"data,omitempty"`
}

// AssertGetDeviceOperations200ResponseRequired checks if the required fields are not zero-ed
func AssertGetDeviceOperations200ResponseRequired(obj GetDeviceOperations200Response) error {
	for _, el := range obj.Data {
		if err := AssertPaginatedDeviceOperationRequired(el); err != nil {
			return err
		}
	}
	return nil
}

// AssertGetDeviceOperations200ResponseConstraints checks if the values respects the defined constraints
func AssertGetDeviceOperations200ResponseConstraints(obj GetDeviceOperations200Response) error {
	return nil
}
