/*
 * LwM2M NB APIs
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi


import (
	"time"
)



type PaginatedObservationNotificationError struct {

	Type string `json:"type"`

	NotificationId string `json:"notificationId"`

	ServerTimestamp time.Time `json:"serverTimestamp"`
}

// AssertPaginatedObservationNotificationErrorRequired checks if the required fields are not zero-ed
func AssertPaginatedObservationNotificationErrorRequired(obj PaginatedObservationNotificationError) error {
	elements := map[string]interface{}{
		"type": obj.Type,
		"notificationId": obj.NotificationId,
		"serverTimestamp": obj.ServerTimestamp,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertPaginatedObservationNotificationErrorConstraints checks if the values respects the defined constraints
func AssertPaginatedObservationNotificationErrorConstraints(obj PaginatedObservationNotificationError) error {
	return nil
}
