/*
 * LwM2M NB APIs
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi




type CreateOperationWithValue struct {

	Operation string `json:"operation"`

	Targets []CreateOperationWithValueTargetsInner `json:"targets"`
}

// AssertCreateOperationWithValueRequired checks if the required fields are not zero-ed
func AssertCreateOperationWithValueRequired(obj CreateOperationWithValue) error {
	elements := map[string]interface{}{
		"operation": obj.Operation,
		"targets": obj.Targets,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	for _, el := range obj.Targets {
		if err := AssertCreateOperationWithValueTargetsInnerRequired(el); err != nil {
			return err
		}
	}
	return nil
}

// AssertCreateOperationWithValueConstraints checks if the values respects the defined constraints
func AssertCreateOperationWithValueConstraints(obj CreateOperationWithValue) error {
	return nil
}
