/*
 * LwM2M NB APIs
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi




type ObservationAllOfTargets struct {

	Path string `json:"path,omitempty"`
}

// AssertObservationAllOfTargetsRequired checks if the required fields are not zero-ed
func AssertObservationAllOfTargetsRequired(obj ObservationAllOfTargets) error {
	return nil
}

// AssertObservationAllOfTargetsConstraints checks if the values respects the defined constraints
func AssertObservationAllOfTargetsConstraints(obj ObservationAllOfTargets) error {
	return nil
}
