/*
 * LwM2M NB APIs
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi




type CreateObservation struct {

	Targets []CreateObservationTargetsInner `json:"targets,omitempty"`
}

// AssertCreateObservationRequired checks if the required fields are not zero-ed
func AssertCreateObservationRequired(obj CreateObservation) error {
	for _, el := range obj.Targets {
		if err := AssertCreateObservationTargetsInnerRequired(el); err != nil {
			return err
		}
	}
	return nil
}

// AssertCreateObservationConstraints checks if the values respects the defined constraints
func AssertCreateObservationConstraints(obj CreateObservation) error {
	return nil
}
