/*
 * LwM2M NB APIs
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi


import (
	"time"
)



type SingleOperationErrorReport struct {

	Path string `json:"path"`

	FailureReason string `json:"failureReason"`

	ServerTimestamp time.Time `json:"serverTimestamp"`
}

// AssertSingleOperationErrorReportRequired checks if the required fields are not zero-ed
func AssertSingleOperationErrorReportRequired(obj SingleOperationErrorReport) error {
	elements := map[string]interface{}{
		"path": obj.Path,
		"failureReason": obj.FailureReason,
		"serverTimestamp": obj.ServerTimestamp,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertSingleOperationErrorReportConstraints checks if the values respects the defined constraints
func AssertSingleOperationErrorReportConstraints(obj SingleOperationErrorReport) error {
	return nil
}
