/*
 * LwM2M NB APIs
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi


import (
	"time"
)



type PaginatedDeviceOperation struct {

	// The type of the operation
	Operation string `json:"operation,omitempty"`

	// The status of the operation
	Status string `json:"status,omitempty"`

	CompletenessDate time.Time `json:"completenessDate,omitempty"`

	OperationId string `json:"operationId,omitempty"`
}

// AssertPaginatedDeviceOperationRequired checks if the required fields are not zero-ed
func AssertPaginatedDeviceOperationRequired(obj PaginatedDeviceOperation) error {
	return nil
}

// AssertPaginatedDeviceOperationConstraints checks if the values respects the defined constraints
func AssertPaginatedDeviceOperationConstraints(obj PaginatedDeviceOperation) error {
	return nil
}
